destinationcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('destinations/', views.destinations_index, name='index'),
    path('destinations/<int:destination_id>/', views.destinations_detail, name='detail'),
    path('destinations/create/', views.DestinationCreate.as_view(), name='destinations_create'),
    path('destinations/<int:pk>/update/', views.DestinationUpdate.as_view(), name='destinations_update'),
    path('destinations/<int:pk>/delete/', views.DestinationDelete.as_view(), name='destinations_delete'),
    path('destinations/<int:destination_id>/add_weather/', views.add_weather, name='add_weather'),
    path('destinations/<int:destination_id>/add_photo/', views.add_photo, name='add_photo'),
    path('destinations/<int:destination_id>/assoc_activity/<int:activity_id>/', views.assoc_activity, name='assoc_activity'),
    path('destinations/<int:destination_id>/unassoc_activity/<int:activity_id>/', views.unassoc_activity, name='unassoc_activity'),
    path('activities/', views.ActivityList.as_view(), name='activities_index'),
    path('activities/<int:pk>/', views.ActivityDetail.as_view(), name='activities_detail'),
    path('activities/create/', views.ActivityCreate.as_view(), name='activities_create'),
    path('activities/<int:pk>/update/', views.ActivityUpdate.as_view(), name='activities_update'),
    path('activities/<int:pk>/delete/', views.ActivityDelete.as_view(), name='activities_delete'),

 ]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date


STATUSES = (
    ('S', 'Sunny'),
    ('R', 'Rainy'),
    ('C', 'Cloudy')
)

class Activity(models.Model):
  name = models.CharField(max_length=50)
 
  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('activities_detail', kwargs={'pk': self.id})



class Destination(models.Model):
    location = models.CharField(max_length=100)
    continent = models.CharField(max_length=100)
    climate = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    activities = models.ManyToManyField(Activity)

    def __str__(self):
        return f'{self.location} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'destination_id': self.id})


class Weather(models.Model):
  date = models.DateField()
  status = models.CharField(
    max_length=1,
	 choices=STATUSES,
	 default=STATUSES[0][0]
  )
  
  destination = models.ForeignKey(Destination, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_status_display()} on {self.date}"
    class Meta:
      ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo(s) of destination_id: {self.destination_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Weather

class WeatherForm(ModelForm):
  class Meta:
    model = Weather
    fields = ['date', 'status']

main_app/views.py
import uuid
import boto3
import os
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Destination, Activity, Photo
from .forms import WeatherForm




def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def destinations_index(request):
  destinations = Destination.objects.all()
  return render(request, 'destinations/index.html', {
    'destinations': destinations
  })

def destinations_detail(request, destination_id):
  destination = Destination.objects.get(id=destination_id)
  id_list = destination.activities.all().values_list('id')
  # Now we can query for activities whose ids are not in the list using exclude
  activities_destination_doesnt_have = Activity.objects.exclude(id__in=id_list)
  weather_form = WeatherForm()
  return render(request, 'destinations/detail.html', {
    'destination': destination, 'weather_form': weather_form,
    'activities': activities_destination_doesnt_have
  })

class DestinationCreate(CreateView):
  model = Destination
  fields = ['location','continent', 'climate', 'language']
 
class DestinationUpdate(UpdateView):
  model = Destination
  fields = ['location','continent', 'climate', 'language']

class DestinationDelete(DeleteView):
  model = Destination
  success_url = '/destinations'

def add_weather(request, destination_id):
  # create a ModelForm instance using the data in request.POST
  form = WeatherForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the destination_id assigned
    new_weather = form.save(commit=False)
    new_weather.destination_id = destination_id
    new_weather.save()
  return redirect('detail', destination_id=destination_id)

class ActivityList(ListView):
  model = Activity

class ActivityDetail(DetailView):
  model = Activity

class ActivityCreate(CreateView):
  model = Activity
  fields = '__all__'

class ActivityUpdate(UpdateView):
  model = Activity
  fields = ['name']

class ActivityDelete(DeleteView):
  model = Activity
  success_url = '/activities'

def assoc_activity(request, destination_id, activity_id):
  # Note that you can pass a activity's id instead of the whole activity object
  Destination.objects.get(id=destination_id).activities.add(activity_id)
  return redirect('detail', destination_id=destination_id)

def unassoc_activity(request, destination_id, activity_id):
  # Note that you can pass a activity's id instead of the whole activity object
  Destination.objects.get(id=destination_id).activities.remove(activity_id)
  return redirect('detail', destination_id=destination_id)

def add_photo(request, destination_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            # build the full url string
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            # we can assign to destination_id or destination (if you have a destination object)
            Photo.objects.create(url=url, destination_id=destination_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('detail', destination_id=destination_id)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>About the Developer</h1>
 <hr>
    <h4>
        Hi! I'm Sandy McGee, a results-driven full-stack software engineer with a strong Teaching/Education background. My expertise lies in creating efficient, user-friendly applications. I'm deeply passionate about topics such as special education, animal rescue, travel, and environmental conservation through technology. 
        My goal is to  build purposeful software solutions for a brighter future.
    </h4>
    <h3>Hire Me</h3>
<p>sandyasomcgee@gmail.com</p>
<p><a href="https://www.linkedin.com/in/sandymcgee-memphis/">LinkedIn</a></p>


{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Destination Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet"  href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Arimo:wght@500&family=Bebas+Neue&family=Comfortaa&family=Concert+One&family=Manrope:wght@500&family=Monofett&family=Oxygen&family=Permanent+Marker&family=Poller+One&family=Rubik+Bubbles&display=swap" rel="stylesheet">

</head>
<body>
  <header class="navbar-fixed">
    <nav style="background-color: rgba(18, 131, 60, 0.428);">
  
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}">&nbsp;&nbsp;Destination Planner</a></li>
        </ul>
        <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'activities_create' %}">Add an Activity</a></li>
            <li><a href="{% url 'activities_index' %}">View All Activities</a></li>
            <li><a href="{% url 'destinations_create' %}">Add a Destination</a></li>
            <li><a href="{% url 'index' %}">View All Destinations</a></li>
            <li><a href="{% url 'home' %}">Home</a></li>
        </ul>
      </div>
   </nav>
  </header>

  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer" style="background-color: rgba(18, 131, 60, 0.428);">
    <div class="right">All Rights Reserved, &copy; 2023 Destination Planner &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/destinations/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>{{ destination.location}} Details</h1>


<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ destination.location}}</span>
        <p>Continent: {{ destination.continent }}</p>
        <p>Climate: {{ destination.climate }}</p>
        <p>Language: {{ destination.language }}</p>
    </div>
      <div class="card-action">
        <a href="{% url 'destinations_update' destination.id %}">Edit</a>
        <a href="{% url 'destinations_delete' destination.id %}">Delete</a>
      </div>
    </div>
    {% for photo in destination.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
       {% empty %}
       <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' destination.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <button type="submit" class="btn">Upload Photo</button>
  </form>
  </div>
  <div class="col s6">
    <form action="{% url 'add_weather' destination.id %}" method="POST">
      {% csrf_token %}
      {{ weather_form.as_p }}
      <input type="submit" class="btn" value="Log Weather">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Weather Status</th></tr>
      </thead>
      <tbody>
        {% for weather in destination.weather_set.all %}
          <tr>
            <td>{{weather.date}}</td>
            <td>{{weather.get_status_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- New Markup Above -->
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>Activities for {{ destination.location }}</h3>
    {% if destination.activities.count %}
      {% for activity in destination.activities.all %}
    <div class="card">
        <div class="card-content">
            <span class="card-title">
               <span style="color: {{ activity.name }}">{{ activity.name }}</span>
            </span>
        </div>
        <div class="card-action">
            <form action="{% url 'unassoc_activity' destination.id activity.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
        </div>
      </div>
      {% endfor %}
    {% else %}
      <h5>No activities 😿</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Activities</h3>
    {% if activities.count %}
      {% for activity in activities.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span style="color: {{ activity.name }}">{{ activity.name }}</span>
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_activity' destination.id activity.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5> All Activities Added for {{destination.location}} </h5>
    {% endif %}
  </div>
</div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  const selectEl = document.getElementById('id_status');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/destinations/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Destination List</h1>

{% for destination in destinations %}
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ destination.location }}</span>
      <p>Continent: {{ destination.continent }}</p>
      <p>Climate: {{ destination.climate }}</p>
      <p>Language: {{ destination.language }}</p>
    
    </div>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Home</h1>
    <p>Welcome to <strong><em><a href="#" title="Destination Planner">Destination Planner</a></em></strong>,
    your ultimate travel companion! Whether you're an adventurous globetrotter or a leisurely wanderer, our website is here to make your travel dreams come true. 
    Plan your visit to breathtaking destinations and create exciting itineraries, all with the ease of our tools. 
    Plan your future journeys or log your past ones using our intuitive trip planner and recorder features, where you can customize every detail of 
    your adventure. With Destination Planner, your next unforgettable travel experience is just a click away!</p>
{% endblock %}

main_app/templates/main_app/activity_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Activity</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'activities_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/activity_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Activity Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ activity.name }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'activities_update' activity.id %}">Edit</a>
        <a href="{% url 'activities_delete' activity.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/activity_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Activity</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/activity_list.html
{% extends 'base.html' %}
{% block content %}

<h1>All Activities</h1>

{% for activity in activity_list %}
  <a href="{% url 'activities_detail' activity.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ activity.name }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/destination_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Destination</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.location }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' destination.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/destination_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.location}}?</span></h1>
{% else %}
<h1>Add Destination</h1>
{% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}